### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by NormalFery** [Pridecraft-Studios/joy#17]
- [ ] Bump dependencies (MAVAPI) to 1.21.2+
- [ ] Bump mod to 1.21.2+ and test pridexolotls in current implementation
- [ ] Implement all Bundles of Pride from pridepack as separate items
- [ ] Add further entries as we go along

**Comment by blryface** [comment]
I think we should have these separated by sections, and include our plans for Joy features
