### ISSUE TITLE
[TODO] Content

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/joy#19]
This is an issue used to track our progress in Joy's `Content` features. It should be synced to `TODO.md`.

- [ ] All Bundles from Pridepack as separate items
- [ ] Pride cakes
    - [ ] Rainbow cherries
    - [ ] Rainbow inside, red cherries
    - [ ] Rainbow inside, rainbow cherries
- [X] All pride candles
- [X] All pride beds
- [ ] All pride entity variants
- [X] All paintings from Pridepack
- [X] All splashes from Pridepack
- [ ] Pride banners (different from Minecraft's actual banners)
- [ ] Pride shulker boxes
- [ ] Pride armor trims
- [X] All music from the Joy OST
- [ ] Music discs with music made by Ministumpy
- [X] Add a Blåhaj
- [ ] "Pride Table" block to help with crafting of Pride items¹
- [ ] Joy Biomes²
- [ ] Pride dyes to help with recipes for the Pride Items
- [ ] More variants of Pridepack entities
- [ ] Rare music disk using WorldWidePixel - [Currently untitled `366` song]
