### ISSUE TITLE
[TODO] Technical

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/joy#20]
This is an issue used to track our progress in Joy's `Technical` features. It should be synced to `TODO.md`.

- [ ] Proper configs
    - [ ] Configurable Main Menu changes
        - [ ] Minecraft Logo
        - [ ] Panorama
        - [ ] Splashes
        - [ ] Mojang Splash
    - [ ] Configurable spawn rate?
- [ ] Bump mod and libraries to 1.20.4, and make sure all features work properly.
- [ ] Custom UI and functionality for the "Pride Table"¹
- [ ] Crafting recipes for all Pride items (Crafting Table, "Pride Table"¹, Furnace etc)
- [ ] Balancing of rarity of Joy Mod's content
