### ISSUE TITLE
[TODO] Misc

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/joy#21]
This is an issue used to track our progress in Joy's `Misc` features. It should be synced to `TODO.md`.

- [ ] Joy Wiki
- [ ] Integration with/in other Pridecraft projects
- [ ] Credit everyone involved with the project properly
- [ ] Mention other people's work on Pridecraft somewhere
- [ ] Hide silly stuff in the files
